// config.js — API endpoint configuration
// Auto-generated by deploy.sh — do not edit manually

window.REST_API_URL  = 'https://8hk31m5jd5.execute-api.us-east-1.amazonaws.com';
window.WEBSOCKET_URL = 'wss://j25iwgd3t0.execute-api.us-east-1.amazonaws.com/prod';
