#!/usr/bin/env bash
# deploy.sh — Build, deploy, and upload frontend for the Spinning Wheel app
# Usage: ./deploy.sh

set -euo pipefail

PROFILE="workshop"
REGION="us-east-1"
STACK="workshop"

echo "==> Building SAM application..."
sam build

echo "==> Deploying SAM stack..."
sam deploy --profile "$PROFILE"

echo "==> Fetching stack outputs..."
REST_API_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" \
  --region "$REGION" \
  --profile "$PROFILE" \
  --query "Stacks[0].Outputs[?OutputKey=='RestApiUrl'].OutputValue" \
  --output text)

WEBSOCKET_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" \
  --region "$REGION" \
  --profile "$PROFILE" \
  --query "Stacks[0].Outputs[?OutputKey=='WebSocketUrl'].OutputValue" \
  --output text)

BUCKET_NAME=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" \
  --region "$REGION" \
  --profile "$PROFILE" \
  --query "Stacks[0].Outputs[?OutputKey=='FrontendBucketName'].OutputValue" \
  --output text)

CLOUDFRONT_URL=$(aws cloudformation describe-stacks \
  --stack-name "$STACK" \
  --region "$REGION" \
  --profile "$PROFILE" \
  --query "Stacks[0].Outputs[?OutputKey=='CloudFrontUrl'].OutputValue" \
  --output text)

echo "  REST API URL : $REST_API_URL"
echo "  WebSocket URL: $WEBSOCKET_URL"
echo "  S3 Bucket    : $BUCKET_NAME"
echo "  CloudFront   : $CLOUDFRONT_URL"

echo "==> Updating config.js with live endpoints..."
cat > config.js <<EOF
// config.js — API endpoint configuration
// Auto-generated by deploy.sh — do not edit manually

window.REST_API_URL  = '$REST_API_URL';
window.WEBSOCKET_URL = '$WEBSOCKET_URL';
EOF

echo "==> Uploading frontend files to S3..."
aws s3 sync . "s3://$BUCKET_NAME" \
  --profile "$PROFILE" \
  --region "$REGION" \
  --exclude "*" \
  --include "index.html" \
  --include "register.html" \
  --include "tests.html" \
  --include "config.js" \
  --delete

echo "==> Invalidating CloudFront cache..."
DISTRIBUTION_ID=$(aws cloudfront list-distributions \
  --profile "$PROFILE" \
  --query "DistributionList.Items[?DomainName=='${CLOUDFRONT_URL#https://}'].Id" \
  --output text)

aws cloudfront create-invalidation \
  --distribution-id "$DISTRIBUTION_ID" \
  --paths "/*" \
  --profile "$PROFILE" \
  --output table

echo ""
echo "✅ Deployment complete!"
echo "   Live URL: $CLOUDFRONT_URL"
