version = 0.1

[default.deploy.parameters]
stack_name = "workshop"
resolve_s3 = true
s3_prefix = "workshop"
profile = "workshop"
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "us-east-1"
